name: Build and Release

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-


      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Debug target directory
      - name: List target directory contents
        run: ls -al ./target
        continue-on-error: true

      # Step 6: Upload .vmod file artifact
      - name: Upload .vmod file artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmod-file
          path: target/*.vmod

  create-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    needs: build

    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
      RELEASE_NOTES: ${{ steps.process_release_notes.outputs.body }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Get version dynamically from pom.xml
      - name: Get version dynamically from pom.xml
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=<version>)[^<]+' pom.xml | head -n 1)
          echo "::set-output name=VERSION::$VERSION"

      # Step 3: Check release notes and prepare for GitHub Release
      - name: Check for correct version and read release-notes.md
        id: process_release_notes
        run: |
          VERSION=$(grep -oP '(?<=<version>)[^<]+' pom.xml | head -n 1)
          NOTES_FILE="dist/release-notes.md"
          if [[ ! -f "$NOTES_FILE" ]]; then
            echo "Error: $NOTES_FILE not found."
            exit 1
          fi
          if ! head -n 5 "$NOTES_FILE" | grep -q "Version ${VERSION}"; then
            echo "Error: Version ${VERSION} not found in the first 5 lines of $NOTES_FILE."
            exit 1
          fi
          RELEASE_NOTES=$(cat "$NOTES_FILE")
          echo "::set-output name=body::$RELEASE_NOTES"

  update-website:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: vasl-developers/vasl-website
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: gh-pages

      - name: Update download.htm
        run: |
          VERSION=${{ needs.create-release.outputs.VERSION }}
          UPDATED_DATE=$(date '+%B %d, %Y')
          RELEASE_NOTES=${{ needs.create-release.outputs.body }}
          NEW_DIV="<div class='well table'>
          <a id='download${VERSION//./}' class='track btn btn-large btn-primary' href='${{ env.DOWNLOAD_LINK }}'>VASL ${VERSION}</a>
          <h2 class='pull-right'>Updated ${UPDATED_DATE}</h2>
          <li>${RELEASE_NOTES}</li>
          </div>"

          sed -i "/<div class='well table'>/h; \$!b; x; s@</div>@${NEW_DIV}</div>@; x; P; D" download.htm

      - name: Wait for manual approval
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: manual-approval

      - name: Commit and push changes (after approval)
        if: ${{ github.event.inputs.approval == 'approved' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add download.htm
          git commit -m "Update download.htm with VASL ${VERSION}"
          git push origin gh-pages
